In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### 1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [3]:
arr = [1,20,300,4000,50000]
pd.Series(arr)

0        1
1       20
2      300
3     4000
4    50000
dtype: int64

#### 2.Write a Python program to convert a Panda module Series to Python list and its type.

In [6]:
srs = pd.Series([12,23,34,45,56,67,78,89,90])
print(srs, type(srs))
lst = list(srs)
print(lst, type(lst))

0    12
1    23
2    34
3    45
4    56
5    67
6    78
7    89
8    90
dtype: int64 <class 'pandas.core.series.Series'>
[12, 23, 34, 45, 56, 67, 78, 89, 90] <class 'list'>


#### 3.Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [10]:
s1 = pd.Series((60,70,80,90,100))
s2 = pd.Series([10,20,30,40,50])
print('Series Addition: \n', s1+s2)
print('Series Subtraction: \n', s1-s2)
print('Series Multiplication: \n', s1*s2)
print('Series Division: \n', s1/s2)

Series Addition: 
 0     70
1     90
2    110
3    130
4    150
dtype: int64
Series Subtraction: 
 0    50
1    50
2    50
3    50
4    50
dtype: int64
Series Multiplication: 
 0     600
1    1400
2    2400
3    3600
4    5000
dtype: int64
Series Division: 
 0    6.000000
1    3.500000
2    2.666667
3    2.250000
4    2.000000
dtype: float64


#### 4 .Write a Python program to compare the elements of the two Pandas Series.

In [15]:
s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5))
print('Series s1: \n',s1)
print('Series s2: \n',s2)
print('s1 is less than s2 -', s1<s2)
print('s2 is less than s1 -', s1>s2)
print('s1 is equal to s2 -', s1==s2)

Series s1: 
 0    0.826486
1    0.102197
2    0.281944
3    0.985799
4    0.584501
dtype: float64
Series s2: 
 0    0.041476
1    0.244295
2    0.974728
3    0.518654
4    0.927193
dtype: float64
s1 is less than s2 - 0    False
1     True
2     True
3    False
4     True
dtype: bool
s2 is less than s1 - 0     True
1    False
2    False
3     True
4    False
dtype: bool
s1 is equal to s2 - 0    False
1    False
2    False
3    False
4    False
dtype: bool


#### 5.Write a Python program to create and display a Data Frame from a specified dictionary data which has the index labels

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James',
'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no',
'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [16]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
print(exam)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


#### 6.Write a Python program to select the specified columns (score and attempts) and rows(1,3,5,6) from a given Data Frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [50]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
exam[['score','attempts']].iloc[[1,3,5,6]]

score  attempts
b    9.0         3
d    NaN         3
f   20.0         3
g   14.5         1

#### 7.Write a Python program to select the rows the score is between 15 and 20 (inclusive).

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [61]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
exam.score[(exam['score']>=15) & (exam['score']<=20)]

c    16.5
f    20.0
j    19.0
Name: score, dtype: float64

### 8. Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [62]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
exam[(exam['attempts']<2) & (exam['score']>15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

#### 9. Write a Python program to sort the data frame first by 'name' in descending order, then by 'score' in ascending order.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [43]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
exam.sort_values(by=['name', 'score'],ascending=[False,True])

name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

#### 10. Write a Python program to insert a new column in existing Data Frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [83]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
exam['new_column'] = 'new_data'
exam

name  score  attempts qualify new_column
a  Anastasia   12.5         1     yes   new_data
b       Dima    9.0         3      no   new_data
c  Katherine   16.5         2     yes   new_data
d      James    NaN         3      no   new_data
e      Emily    9.0         2      no   new_data
f    Michael   20.0         3     yes   new_data
g    Matthew   14.5         1     yes   new_data
h      Laura    NaN         1      no   new_data
i      Kevin    8.0         2      no   new_data
j      Jonas   19.0         1     yes   new_data

#### 11.Write a Python program to change the name 'James' to 'Suresh' in name column of the data frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [86]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam = pd.DataFrame(exam_data, index=labels)
exam.name[exam['name'] == 'James'] = 'Suresh'
exam

<ipython-input-86-71081158c423>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exam.name[exam['name'] == 'James'] = 'Suresh'


name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes